version: "3.9"

services:
  postgres:
    build:
      context: db
    env_file: .env
    ports: 
      - "5432:5432"
    volumes:
      - loonie:/var/lib/postgresql/data
  backend:
    build:
      context: backend
    env_file: .env
    depends_on:
      - "postgres"
    volumes:
      - loonie:/root


volumes:
  loonie:




