services:
  backend:
    build:
      context: ./backend
    env_file: .env
    depends_on:
      - db

  # frontend:
  #   build:
  #     context: ./client
  #   volumes:
  #     - ./react:/root
  #   ports:
  #     - "3000:3000"

  db:
    build:
      context: ./db
    env_file: .env
    ports: 
      - "5433:5433"
