#!/bin/sh

DIR=$(dirname "$0")

docker-compose -f $DIR/../docker-compose.yml exec db migrate -path="/docker-entrypoint-initdb.d/schema/" -database="postgres://postgres@/postgres?host=/var/run/postgresql/" $@