#!/bin/sh

DIR=$(dirname "$0")

docker cp $DIR/migrations postgres:./migrations/

docker-compose -f $DIR/../docker-compose.yml exec postgres migrate -path="/migrations/" -database="postgres://postgres@/loonie?host=/var/run/postgresql/" $@